### PR TITLE
Add a set of predictions

### PR DESCRIPTION
**Pull request by bgyori**
This is a set of predicted mappings between MeSH supplementary terms and HGNC entries. The only difference in structure is that I added a column for "method" which can describe the type of approach using which the mappings were found. @cthoyt any other columns we should add?

### CODE REVIEW

**Comment by cthoyt** [comment]
Does it need a type=predicted then method=lexical column? Since it's a separate file for predicted, I think you can just have a type=lexical column

**Comment by cthoyt** [comment]
It's nice to have ORCID identifiers so you know who made each contribution (without having to worry about git histories) but I think it would also be nice to have a link to the script that made these too. Alternatively, we could maintain information about where the predictions come from in the README

**Comment by bgyori** [comment]
Alright, I will remove the method column and add a link to a commit-specific script version. Also, now that I think of it, it may be more appropriate to construct these mappings to UniProt (i.e., human proteins) rather then HGNC (i.e., human genes).

**Comment by cthoyt** [comment]
@bgyori good point! Can't start mixing up proteins and genes from the beginning ;)

Do you think that we should put the scripts that generate these mappings in this repo,assuming they're able to simply reuse components from other repos like Gilda and ProtMapper?

**Comment by bgyori** [comment]
Okay, so I replaced the ORDIC with a URL pointing to the script that generated the predictions, and made the mapping to UniProt instead of HGNC.

**Pull request merged**
