### PR TITLE
Add WikiPathways and Reactome mappings

### LINKED ISSUE #31: Species specific mappings
I was starting to do WikiPathways and Reactome mappings to GO and MeSH, but both WikiPathways and Reactome have species-specific identifiers while GO and MeSH do not. Should we make mappings between these?

Perhaps we should start including optional species information in the predictions file for both the source and target when available

### PR DESCRIPTION
**Pull request by cthoyt**
I'd like to use this to generate WikiPathways and Reactome mappings to GO and MeSH.

This PR closes #31 by introducing the relation `speciesSpecific` which has similar semantics to `skos:exactMatch` except it's unidirectional, meaning that the subject is a species-specific exact match of the object of the triple.

I curated lots of non-trivial false mappings, notably including false mappings between pathways and diseases as well as pathways and their subject matter (e.g., photoreceptor pathway and photoreceptors)

I curated all of the WikiPathways connections, but just the human ones for Reactome so far. There's a standardized nomenclature in Reactome so it might be better to automatically transfer annotations based on pathway code (e.g. R-HSA-1234 is the same pathway as R-BOS-1234). This PR is getting big so it might be better to do that in a later PR.

This PR also adds the ability to show the relation in the curation interface, since it's now handling more than one type of relation.

### CODE REVIEW

**Comment by bgyori** [comment]
I used a few different heuristics when putting together the "original" mappings prediction script at https://github.com/indralab/gilda/blob/master/scripts/generate_mesh_mappings.py, like stratifying MeSH terms by type, looking for canonical name matches, length of match, avoiding many-to-many ambiguous mappings etc. We can of course just look for lexical overlaps between arbitrary name spaces but in many cases I expect we will have to do some namespace-specific customizations to avoid lots of false positives (or negatives for that matter).

**Comment by cthoyt** [comment]
@bgyori i've slimmed down the scope of this PR to just be about pathway curation. let me know what you think if you get a chance to take a look at it

**Review by bgyori — APPROVED** [review]
I think this is good! It looks like the script is implemented such that Gilda is loaded with the default configuration. If you have a specific set of target name spaces in mind, you can also instantiate a custom Grounder instance with just those name spaces loaded e.g., GO and MESH. That is what I did for the `pr`-`uniprot.chain` mappings, for instance.

I like the `speciesSpecific` relation, we will have to check at some point if any of the existing mappings are `speciesSpecific` that were originally curated as `skos:exactMatch`.

**Comment by cthoyt** [comment]
> I think this is good! It looks like the script is implemented such that Gilda is loaded with the default configuration. If you have a specific set of target name spaces in mind, you can also instantiate a custom Grounder instance with just those name spaces loaded e.g., GO and MESH. That is what I did for the `pr`-`uniprot.chain` mappings, for instance.
> 
> I like the `speciesSpecific` relation, we will have to check at some point if any of the existing mappings are `speciesSpecific` that were originally curated as `skos:exactMatch`.

That makes sense about using a non-default gilda configuration (I may have even contributed some of that code 🙃), but I see some value to identifying false positives and curating the as well - I think there's a lot to be said later about the strangeness of naming conventions

I think MeSH-HGNC mappings are all up for consideration later, since HGNC doesn't really represent proteins

**Pull request merged**
